<?php
if($_SERVER['HTTP_HOST']=='localhost'){
	$base_url="http://localhost/theembroideryshoppe/";
}else{
	$base_url="https://www.theembroideryshoppe.com/";
}
$write = Mage::getSingleton('core/resource')->getConnection('core_write');
$keyword="";
$where="";
//echo "<pre>";
//print_r($_POST);
if(isset($_POST['submit'])){
	 $keyword=$_POST['keyword'];
	 $where="and title like '%".$keyword."%' or companyname like '%".$keyword."%'";
	
}

$readresult=$write->query("select count(*) as count from uploadlogo where status='1' $where order by title ASC ");
$result=$readresult->fetch();
$per_page = 9; 
//echo "<pre>";
//print_r($readresult);
//$sql = "select * from messages";
//$result = mysql_query($sql);
$count = $result['count'];
$pages = ceil($count/$per_page)
?>

            
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.3.0/jquery.min.js"></script>

<table>
<tr>
<td>Search By Name Or Company Name
<form name="SearchForm" method="post" action="<?php echo $base_url?>logo-gallery">
<input type="text"  maxlength="100" value="<?php echo $keyword;?>" name="keyword" style="font-size: 12px !important;" size="50px" />
<input type="submit" name="submit" value="submit" class="form-button" />
<a href="<?php echo $base_url;?>logo-gallery"><input type="button" name="reset"  value="reset" class="form-button"/></a>

</td>
</tr>
</table>
<div id="loading" ></div>
<div id="content" ></div>
<ul id="pagination" class="logop">
<?php
//Pagination Numbers
for($i=1; $i<=$pages; $i++)
{
echo '<li id="'.$i.'">'.$i.'</li>';
}
?>
</ul>
<script>
$(document).ready(function()
{
	
//Display Loading Image
function Display_Load()
{
$("#loading").fadeIn(900,0);
$("#loading").html('<img src="<?php echo $base_url;?>bigLoader.gif" />');
}
//Hide Loading Image
function Hide_Load()
{
$("#loading").fadeOut('slow');
};

//Default Starting Page Results
$("#pagination li:first")
.css({'color' : '#FF0084'}).css({'border' : 'none'});
Display_Load();
$("#content").load("<?php echo $base_url;?>logo_data.php?page=1&keyword=<?php echo urlencode($keyword);?>", Hide_Load());

//Pagination Click
$("#pagination li").click(function(){
Display_Load();
//CSS Styles
$("#pagination li")
.css({'border' : 'solid #dddddd 1px'})
.css({'color' : '#0063DC'});

$(this)
.css({'color' : '#FF0084'})
.css({'border' : 'none'});

//Loading Data
var pageNum = this.id;
$("#content").load("<?php echo $base_url;?>logo_data.php?page=" + pageNum, Hide_Load());
});

});

</script>
<style>
#loading
{ 

position: absolute;
}
.logop li
{ 
list-style: none; 
float: left; 
margin-right: 16px; 
padding:5px; 
border:solid 1px #dddddd;
color:#0063DC; 
}
.logop li:hover
{ 
color:#FF0084; 
cursor: pointer; 
}
</style>