<?php
$write = Mage::getSingleton('core/resource')->getConnection('core_write');
$readresult=$write->query("select * from uploadedlogo where status='1' order by title ASC");

?>

<table width="100%" border="0" cellpadding="0" cellspacing="2">
<tr> 
<?php
$i=1;
while($row = $readresult->fetch()){

?>
<td align="center"   valign="top"> 
<img src="<?php echo str_replace('index.php/','',Mage::getBaseUrl());   ?>media/<?php echo $row['filename']; ?>" border="0"><br> <?php echo $row['title']; ?> 
</td>
<?php $i++; if($i==6) { $i==1; echo '</tr>'; } } ?>								
                                              
                              </tr>
              <tr>
                <td colspan="3" >&nbsp;</td>
              </tr>
              

              
              <!-- <tr>
			  
			  			  </tr>-->
            </table>
